CREATE TABLE customers (
    id BIGINT PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE products (
    id BIGINT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    stock INTEGER NOT NULL CHECK (stock >= 0)
);

CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    note VARCHAR(200),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE idempotency_records (
    idempotency_key VARCHAR(120) PRIMARY KEY,
    request_fingerprint VARCHAR(64) NOT NULL,
    order_id BIGINT NOT NULL UNIQUE REFERENCES purchase_orders(id)
);

CREATE TABLE idempotency_lock_buckets (
    bucket_id INTEGER PRIMARY KEY
);

CREATE INDEX idx_purchase_orders_customer_created
    ON purchase_orders(customer_id, created_at DESC);

INSERT INTO customers(id, username) VALUES (1, 'alice');
INSERT INTO customers(id, username) VALUES (2, 'bob');
INSERT INTO products(id, name, stock) VALUES (1, 'backend-book', 100);
INSERT INTO idempotency_lock_buckets(bucket_id) VALUES
    (0), (1), (2), (3), (4), (5), (6), (7),
    (8), (9), (10), (11), (12), (13), (14), (15),
    (16), (17), (18), (19), (20), (21), (22), (23),
    (24), (25), (26), (27), (28), (29), (30), (31),
    (32), (33), (34), (35), (36), (37), (38), (39),
    (40), (41), (42), (43), (44), (45), (46), (47),
    (48), (49), (50), (51), (52), (53), (54), (55),
    (56), (57), (58), (59), (60), (61), (62), (63);
